services:

  mysql:
    image: mysql:8.0
    container_name: franquicias-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: franquisias
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: franquicias-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/franquisias?sslMode=DISABLED&allowPublicKeyRetrieval=true
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: 123456

volumes:
  mysql_data:
