# ==========================================
# APLICACION MANEJO DE FRANQUICIAS
# ==========================================
spring.application.name=franquicias

# ==========================================
# CONEXIÓN R2DBC A MYSQL (reactivo)
# ==========================================
spring.r2dbc.url=r2dbc:mysql://localhost:3306/franquicias?sslMode=disabled
spring.r2dbc.username=root
spring.r2dbc.password=123456

# ==========================================
# INICIALIZACIÓN DEL SCHEMA
# ==========================================
spring.sql.init.mode=never